config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'projet/index'

  root 'home#index'

  get 'client/:id' => 'home#show'
  patch 'client/:id' => 'home#update'
  delete 'client/:id' => 'home#destroy'
  get 'client/creation/:id' => 'home#creation'
  post '/client/creation/new/:id' => 'home#clients'

resources :projet 
get 'projet/new/:id' => 'projet#new'
post 'projet/new/client/:id' => 'projet#create'

end

app/models/client.rb
class Client < ActiveRecord::Base

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/


validates :entreprise, presence:{
    message: "Le nom de l'entreprise doit être renseigné !"
  }

validates :nom, presence: {
    message: "Le nom doit être renseigné !"
  }

validates :entreprise, uniqueness: {
    message: "Cette entreprise est déjà dans la base"
  }

validates :email, presence: {
    message: "L'Email doit être renseigné !"
  }

has_many :projects


end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :client
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
before_action :authenticate_user!

  def index
    @clients = Client.all
    @var_id = Client.last.id + 1
    @projets = Project.order(:date)
    @tarifs= Project.where.not(tarif: nil)
  end


   def clients
  @back_url = session[:my_previous_url]
  @creer = Client.create nom: params[:nom], email: params[:email], prenom: params[:prenom], entreprise: params[:entreprise], rue: params[:rue], ville: params[:ville], tel: params[:tel], avatar: params[:avatar], description: params[:description], contrat_type: params[:contrat_type]
  if @creer.valid?
    redirect_to "/"
  flash[ :success ] = "Les éléments ont été mis à jour avec succès"
  else
  redirect_to "/"
  flash[ :nosucces ] = "L'enregistrement n'est pas pris en compte car il manque un ou plusieurs éléments"
  end  
  end

  def creation 
     @var_id = Client.last.id + 1
  end

  def show
    @projets = Project.where(client_id: params[:id])
    @client = Client.find(params[:id])
    @clients = Client.all
  end

def update
    @client = Client.find(params[:id])    
    if @client.update_attributes(user_params)
    redirect_to "/client/#{params[:id]}"
    flash[ :success ] = "Les éléments ont été mis à jour avec succès"
    else 
      render 'show'
    end
  end 


  def destroy
    Client.find(params[:id]).destroy
    Project.where(client_id: params[:id]).destroy_all
    redirect_to "/"
  end

private

def set_book
 @set = Client.find(params[:id])
end
# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

def user_params
  params.require(:client).permit( :nom, :prenom, :entreprise, :email, :rue, :ville, :tel, :avatar, :description, :contrat_type)
end

end

app/controllers/projet_controller.rb
class ProjetController < ApplicationController

  before_action :authenticate_user!

  
  def index
     @projets = Project.all
  end

  def show
@projects = Project.where( client_id: params[:id])
  end

  def new
 @date = Date.today
 @client= Client.find(params[:id])
 @projets = Project.all
  end 

  def edit
@date = Date.today
@projet = Project.find(params[:id])
@projets = Project.where( client_id: params[:id])
  end


def user_params
  params.require(:project).permit( :date, :domaine, :site_type, :multilingue, :avance, :techno_type, :description, :note, :date_avance_2, :date_avance_5, :date_avance_6, :tarif, :duree_crea, :tarif_abo)
end

  def update
  	 @projet = Project.find(params[:id])    
    if @projet.update_attributes(user_params)
    redirect_to "/projet/#{params[:id]}/edit"
    flash[ :success ] = "Les éléments ont été mis à jour avec succès"
    else 
      render 'show'
    end
  end

    def destroy
    Project.find(params[:id]).destroy
    redirect_to "/"
  end

def create
@date = Date.today
@creer_project = Project.create date: @date, domaine: params[:domaine], site_type: params[:site_type], multilingue: params[:multilingue], avance: params[:avance], techno_type: params[:techno_type], description: params[:description], client_id: params[:id]
  if @creer_project.valid?
  redirect_to "/"
  flash[ :success ] = "Le site a été ajouté à la base PoB avec succès"
  else
  redirect_to "/"
  flash[ :nosucces ] = "Une erreure a été identifiée !"
  end
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
	def date_format(date)
   date.strftime("%d/%m/%Y")
end
end

app/helpers/projet_helper.rb
module ProjetHelper
	def options_for_duree
  ['40', '60', '90', '180', 'Durée spéciale']
end
end

app/views/home/creation.html.erb
<% content_for :title, "Création d'une fiche client" %>
<div class="container">
	<div class="col-xs-12 col-md-8">

		<H1>Création d'une fiche client</h1>

       <%= form_tag "/client/creation/new/#{@var_id}" , method: "post" do %>
                      
                            <div class="form-group">
                                <label>Nom * </label>
                                <input type="text" name="nom" class="form-control" placeholder="Nom" >
                                <p class="help-block">Nom du propriétaire de l'entreprise</p>

                            </div>

                            <div class="form-group">
                                <label>Prénom</label>
                             <input type="text" name="prenom" class="form-control" placeholder="Prénom" >

                            </div>

                             <div class="form-group">
                                <label>Nom de l'entreprise *</label>
                                <input type="text" name="entreprise" class="form-control" placeholder="Entreprise ou Raison social" >
                            </div>

                              <div class="form-group">
                                <label>Adresse</label>
                                <input type="text" name="rue" class="form-control" placeholder="Numéro de rue + Rue de facturation" >
                            </div>

                             <div class="form-group">
                                <label>Ville</label>
                                <input type="text" name="ville" class="form-control" placeholder="Ville" >
                            </div>

                             <div class="form-group">
                                <label>Email de l'entreprise *</label>
                                <input type="email" name="email" class="form-control" placeholder="Email" >
                            </div>

                            <div class="form-group">
                                <label>Numéro de tel </label>
                                <input type="text" name="tel" class="form-control" placeholder="EX : 0613707075" >
                            </div>


                            <div class="form-group">
                                <label>Logo de l'entreprise</label>
                              <input type="file" name="avatar">
                            </div>

                            <div class="form-group">
                            <label>Description du project</label>
                            <textarea name="description" class="form-control" rows=20 >
                            </textarea>
                            </div>

          <div class="form-group">
                                <label>Type de demande</label>

                                <div class="radio">
                                    <label>
          <input type="radio" name="contrat_type" value="Création simple" checked > Création simple
                                  </label>
                                </div>

                            <div class="radio">
                                <label>                           
          <input type="radio" name="contrat_type" value="Création + hébergement"> Création avec hébergement
                                </label>
                            </div>

                                <div class="radio">
                                    <label>
         <input type="radio" name="contrat_type" value="Hébergement simple"> Hébergement simple
                                    </label>
                                </div>

                                   <div class="radio">
                                    <label>
         <input type="radio" name="contrat_type" value="Refonte"> Refonte / amélioration de site
                                    </label>
                                </div>


          </div>

                           <input type="submit" class="btn btn-success" value="Enregister"> 
                      
            <% end %>

</div>


	<div style="clear:both;height:20px"></div>

    <a href="/" class="btn btn-primary" >Retourner à l’index</a>
</div>
</div>

app/views/home/show.html.erb
<div class="container">
	<div class="col-xs-12 col-md-8">
		 <h1><%= @client.entreprise_was %>



	                     	<img  class="img-rounded" src="<%= @client.avatar.url(:thumb) %>" />
                             </h1>
                             <div style="clear:both"></div>

             <% if flash[:success] %>
    <div class="alert alert-success animated bounceInUp"><%= flash[:success] %></div>
  <% end %>


       <%= form_for @client, :url => "/client/#{@client.id}", :html => { :multipart => true } do |form| %>

                      
                            <div class="form-group">
                                <label>Nom *</label>
                                <%= form.text_field :nom , class: "form-control" , :placeholder => "Nom"%>
                                
                                 <% if @client.errors[:nom].first %>

                                 <div style="margin:1%" class="alert alert-danger animated shake" role="alert"><%= @client.errors[:nom].first %></div>

                                 <% end %>

                                <p class="help-block">Nom du propriétaire de l'entreprise</p>
                            </div>

                            <div class="form-group">
                                <label>Prénom</label>
                                <%= form.text_field :prenom , class: "form-control" , :placeholder => "Prénom"%>
                            </div>

                             <div class="form-group">
                                <label>Nom de l'entreprise *</label>
                                <%= form.text_field :entreprise , class: "form-control" , :placeholder => "Entreprise ou Raison social"%>
                                 <% if @client.errors[:entreprise].first %>

                                 <div style="margin:1%" class="alert alert-danger animated shake" role="alert"><%= @client.errors[:entreprise].first %></div>

                                 <% end %>

                            </div>
                            

                           <div class="form-group">
                                <label>Email de contact *</label>
                            <%= form.email_field :email, class: "form-control" , :placeholder => "email"%>
                            
                                <% if @client.errors[:email].first %>

                                 <div style="margin:1%" class="alert alert-danger animated shake" role="alert"><%= @client.errors[:email].first %></div>

                                 <% end %>

                            </div>


                              <div class="form-group">
                                <label>Adresse</label>
                                <%= form.text_field :rue , class: "form-control" , :placeholder => "Numéro de rue + Rue de facturation"%>
                            </div>

                             <div class="form-group">
                                <label>Ville</label>
                                <%= form.text_field :ville , class: "form-control" , :placeholder => "Ville"%>
                            </div>

                            <div class="form-group">
                                <label>Numéro de tel </label>
                                <%= form.text_field :tel , class: "form-control" , :placeholder => "Ex : 0613707075"%>
                            </div>


                            <div class="form-group">
                                <label>Logo de l'entreprise</label>
		                        <%= form.file_field :avatar %>
                            </div>

                            <div class="form-group">
                            <label>Description du project</label>
                            <%= form.text_area :description, class: "form-control"  %>

                            </div>

                            <div class="form-group">
                                <label>Type de demande</label>
                                <div class="radio">
                                    <label>
                            <%= form.radio_button :contrat_type, 'Création simple', :checked => true %>  Création Simple
                                    </label>
                                </div>
                                <div class="radio">
                                    <label>
                            <%= form.radio_button :contrat_type, 'Création + hébergement' %>  Création avec hébergement
                                    </label>
                                </div>
                                <div class="radio">
                                    <label>
                            <%= form.radio_button :contrat_type, 'Hébergement simple'  %>  Hébergement Simple
                                    </label>
                                </div>

                                   <div class="radio">
                                    <label>
                            <%= form.radio_button :contrat_type, 'Refonte'  %>  Refonte / amélioration de site
                                    </label>
                                </div>

                            </div>
                           <%= form.submit :Modifier, class: "btn btn-success" %>

            <% end %>
</div>
 <div class="col-xs-6 col-md-4">
    <%= form_tag "/client/#{@client.id}", method: "delete" do %>
    <input data-confirm="Êtes vous sûr de vouloir supprimer ce client ?" data-method="delete" rel="nofollow" type="submit" confirm: "" class=" delete_post btn btn-danger" value="Supprimer cette fiche client" />

	<% end %>

	<div style="clear:both;height:20px"></div>
  <a href="/" class="btn btn-info inline"><i class="glyphicon glyphicon-chevron-left"></i></a>
    <a title="Retour à l'acceuil" href="/projet/create/#{@client.id}" class="btn btn-success"><i title="Créer un nouveau site" class="glyphicon glyphicon-pencil" ></i></a>
    <div style="clear:both;height:20px"></div>
    <table class="table table-striped">
        <tr>
            <th>
                Les Sites 
             </th>
        </tr>   
         <% @projets.each do |projet| %>
         <tr>
            <td>
           <i class="glyphicon glyphicon-ok" style="color:green"></i> <a href="/projet/<%= projet.id %>/edit"> <%= projet.domaine %></a>
            </td>
        </tr>
        <% end %>
    </table> 
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> PoB - Project On Base by Julien Carré</title>

<%= tinymce_assets %>
 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>

  <!-- Latest compiled and minified CSS -->
<link data-no-turbolink="true" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link data-no-turbolink="true" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script data-no-turbolink="true" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">

     <div id="wrapper">


            <% if user_signed_in? %>


        <!-- Navigation -->
        <nav class="navbar navbar-inverse" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Project On Base</a>
            </div>
            <!-- Top Menu Items -->

                       <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active">
                     <%= link_to "Tableau de bord", root_path %>
                    </li>
                    <li>
                     <%= link_to "Les projets PoB", projet_index_path %>
                    </li>
                    <li>
                     <a href="http://desolate-gorge-1378.herokuapp.com/my_app/">Suivi campagnes</a>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa-arrows-v"></i> Les outils de gestion <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo" class="collapse">
                            <li>
                                <a href="http://desolate-gorge-1378.herokuapp.com/my_app/">Suivi campagnes</a>
                            </li>
                            <li>
                            </li>
                        </ul>
                    </li>
            
                </ul>
            </div>

                        <ul class="nav navbar-right top-nav">              
                <li class="dropdown">

                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_user.email %> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                     <%= link_to  "Se déconnecter", destroy_user_session_path, method: :delete, form_class:"fa fa-fw fa-power-off" %><br/>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- /.navbar-collapse -->
        </nav>


            <% end %>



 
<div class="bg-primary notice"><%= notice %></div>
<div class="bg-primary notice"><%= alert %></div>

<%= yield %>

</body>
</html>

app/views/projet/create.html.erb
<div class="container">
	<div class="col-xs-12 col-md-8">
		 <h1><%= @client.entreprise_was %>



	                     	<img  class="img-rounded" src="<%= @client.avatar.url(:thumb) %>" />
                             </h1>
                             <div style="clear:both"></div>

             <% if flash[:success] %>
    <div class="alert alert-success animated bounceInUp"><%= flash[:success] %></div>
  <% end %>


       <%= form_for @client, :url => "/client/#{@client.id}", :html => { :multipart => true } do |form| %>

                      
                            <div class="form-group">
                                <label>Nom *</label>
                                <%= form.text_field :nom , class: "form-control" , :placeholder => "Nom"%>
                                
                                 <% if @client.errors[:nom].first %>

                                 <div style="margin:1%" class="alert alert-danger animated shake" role="alert"><%= @client.errors[:nom].first %></div>

                                 <% end %>

                                <p class="help-block">Nom du propriétaire de l'entreprise</p>
                            </div>

                            <div class="form-group">
                                <label>Prénom</label>
                                <%= form.text_field :prenom , class: "form-control" , :placeholder => "Prénom"%>
                            </div>

                             <div class="form-group">
                                <label>Nom de l'entreprise *</label>
                                <%= form.text_field :entreprise , class: "form-control" , :placeholder => "Entreprise ou Raison social"%>
                                 <% if @client.errors[:entreprise].first %>

                                 <div style="margin:1%" class="alert alert-danger animated shake" role="alert"><%= @client.errors[:entreprise].first %></div>

                                 <% end %>

                            </div>
                            

                           <div class="form-group">
                                <label>Email de contact *</label>
                            <%= form.email_field :email, class: "form-control" , :placeholder => "email"%>
                            
                                <% if @client.errors[:email].first %>

                                 <div style="margin:1%" class="alert alert-danger animated shake" role="alert"><%= @client.errors[:email].first %></div>

                                 <% end %>

                            </div>


                              <div class="form-group">
                                <label>Adresse</label>
                                <%= form.text_field :rue , class: "form-control" , :placeholder => "Numéro de rue + Rue de facturation"%>
                            </div>

                             <div class="form-group">
                                <label>Ville</label>
                                <%= form.text_field :ville , class: "form-control" , :placeholder => "Ville"%>
                            </div>

                            <div class="form-group">
                                <label>Numéro de tel </label>
                                <%= form.text_field :tel , class: "form-control" , :placeholder => "Ex : 0613707075"%>
                            </div>


                            <div class="form-group">
                                <label>Logo de l'entreprise</label>
		                        <%= form.file_field :avatar %>
                            </div>

                            <div class="form-group">
                            <label>Description du project</label>
                            <%= form.text_area :description, class: "form-control"  %>

                            </div>

                            <div class="form-group">
                                <label>Type de demande</label>
                                <div class="radio">
                                    <label>
                            <%= form.radio_button :contrat_type, 'Création simple', :checked => true %>  Création Simple
                                    </label>
                                </div>
                                <div class="radio">
                                    <label>
                            <%= form.radio_button :contrat_type, 'Création + hébergement' %>  Création avec hébergement
                                    </label>
                                </div>
                                <div class="radio">
                                    <label>
                            <%= form.radio_button :contrat_type, 'Hébergement simple'  %>  Hébergement Simple
                                    </label>
                                </div>
                            </div>
                           <%= form.submit :Modifier, class: "btn btn-success" %>

            <% end %>
</div>
 <div class="col-xs-6 col-md-4">
    <%= form_tag "/client/#{@client.id}", method: "delete" do %>
    <input data-confirm="Êtes vous sûr de vouloir supprimer ce client ?" data-method="delete" rel="nofollow" type="submit" confirm: "" class=" delete_post btn btn-danger" value="Supprimer cette fiche client" />

	<% end %>

	<div style="clear:both;height:20px"></div>
    <a href="/" class="btn btn-primary" ><i class="glyphicon glyphicon-repeat"></i></a>
    <a title="Retour à l'acceuil" href="/projet/create/#{@client.id}" class="btn btn-success"><i title="Créer un nouveau site" class="glyphicon glyphicon-pencil" ></i></a>
    <div style="clear:both;height:20px"></div>
    <table class="table table-striped">
        <tr>
            <th>
                Les Sites 
             </th>
        </tr>   
         <% @projets.each do |projet| %>
         <tr>
            <td>
           <i class="glyphicon glyphicon-ok" style="color:green"></i> <a href="/projet/:id"><%= projet.domaine %></a>
            </td>
        </tr>
        <% end %>
    </table> 
</div>
</div>

app/views/projet/index.html.erb
<div id="page-wrapper">

            <div class="container">
              <!-- Page Heading -->
                <div class="row">


<h1>Tous les projets MédiaCarré <BR/>
  <small>Nombre de projets enregistrés :<%= Project.all.count %></small>
  </h1>



            <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title"><i class="glyphicon glyphicon-wrench"></i> Liste des projets</h3>
                            </div>
                            <div class="panel-body">
                                <div class="list-group">
<table class="table table-hover" style="text-align:center">

<tr>
<th width=10% style="text-align:center">Domaine en construction</th>
<th width=10% style="text-align:center">Date de création</th>
<th width=20% style="text-align:center">Entreprise</th>
<th width=10% style="text-align:center">Client</th>
<th style="text-align:center"> Avancée du projet</th>
</tr>
<% @projets.each do |projet| %>
<tr>
<td><a href="/projet/<%= projet.id %>/edit"><i class="fa fa-fw fa-calendar"></i> <%= projet.domaine %>
</td>
<td>
<% if projet.date %>
<%= date_format(projet.date)%>
<% end %>
</td>
<td><%= Client.find(projet.client_id).entreprise %></td>
<td>M.<%= Client.find(projet.client_id).nom %></td>
<td>
<% if projet.avance %> 
<% @value = projet.avance * 25 %>

<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="<%= @value %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @value %>%;">
  </div>
</div>

         <% if @value == 25 %> 
            <p class="text-muted" style="margin:0;font-size:11px">Entretien validé (<%= @value  %> %)</p>
        <% elsif @value == 50 %>
            <p class="text-muted" style="margin:0;font-size:11px">Devis accépté - Mise en route du projet (<%= @value  %> %)</P>
         <% elsif @value == 75 %>
            <p class="text-muted" style="margin:0;font-size:11px">Migration client  - Dernière étape avant livraison (<%= @value  %> %)</p>
         <% elsif @value == 100 %>
            <p class="text-success" style="margin:0;font-size:11px">Projet finalisé  -  (<%= @value  %> %)</p>
         <% end %>   
<% else %>
 <p class="text-warning" style="margin:0;font-size:11px">Entretien non effectué</p>
 <% end %>
</td>
</tr>
 <% end %>    

</table>
                                </div>
<a href="/" class="btn btn-info inline"><i class="glyphicon glyphicon-chevron-left"></i> Retour à l'accueil </a>
                            
                        </div>

</div>

			</div>

		</div>
</div>

app/views/projet/show.html.erb
<div id="page-wrapper">

            <div class="container">
              <!-- Page Heading -->
                <div class="row">


<h1>Fiche projet de monsieur <%= Client.find(params[:id]).nom %>
  <small><%= Client.find(params[:id]).entreprise %></small>
  </h1>

  <p>Tableau récapitulatif des projets en cours du client</p>


		<div class="col-lg-12">

				<table class="table">
				 <% @projects.each do |project| %>
				 <tr>
	<tr>
<td><a href="/projet/<%= project.id %>/edit"><i class="fa fa-fw fa-calendar"></i> <%= project.domaine %>
</td>
<td>
<% if project.date %>
<%= date_format(project.date)%>
<% end %>
</td>
<td>
<% if project.avance %> 
<% @value = project.avance * 25 %>

<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="<%= @value %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @value %>%;">
  </div>
</div>

         <% if @value == 25 %> 
            <p class="text-muted" style="margin:0;font-size:11px">Entretien validé (<%= @value  %> %)</p>
        <% elsif @value == 50 %>
            <p class="text-muted" style="margin:0;font-size:11px">Devis accépté - Mise en route du projet (<%= @value  %> %)</P>
         <% elsif @value == 75 %>
            <p class="text-muted" style="margin:0;font-size:11px">Migration client  - Dernière étape avant livraison (<%= @value  %> %)</p>
         <% elsif @value == 100 %>
            <p class="text-success" style="margin:0;font-size:11px">Projet finalisé  -  (<%= @value  %> %)</p>
         <% end %>   
<% else %>
 <p class="text-warning" style="margin:0;font-size:11px">Entretien non effectué</p>
 <% end %>
</td>
</tr>
 <% end %>    

</table>
                                </div>
<a href="/" class="btn btn-info inline"><i class="glyphicon glyphicon-chevron-left"></i> Retour à l'accueil </a>
 <a href="/client/<%= Client.find(params[:id]).id %>" class="btn btn-default inline"><i class="glyphicon glyphicon-user"></i> Fiche client </a>

     
                           
                        </div>

</div>
		</div>

			</div>

		</div>
</div>